service: saas-boilerplate 

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: us-east-1
  memorySize: 2048 # optional, in MB, default is 1024
  timeout: 30 # optional, in seconds, default is 6

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

custom:
  dotenv:
    include:
      - NODE_ENV
      - MONGO_URL_TEST
      - MONGO_URL
      - AWS_ACCESSKEYID
      - AWS_SECRETACCESSKEY
      - EMAIL_SUPPORT_FROM_ADDRESS
      - URL_APP
      - PRODUCTION_URL_APP

functions:
  sendEmailForNewPost:
    handler: handler.sendEmailForNewPost
