branch-defaults:
  default:
    environment: saas-api-env
environment-defaults:
  async-github1-env:
    branch: null
    repository: null
global:
  application_name: saas-api-app
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
